# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

import sqlparser_pb2 as sqlparser__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in sqlparser_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class SqlParserStub(object):
    """SQL 解析服务 —— 基于 sqlglot
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Health = channel.unary_unary(
                '/sqlparser.SqlParser/Health',
                request_serializer=sqlparser__pb2.HealthRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.HealthReply.FromString,
                _registered_method=True)
        self.Dialects = channel.unary_unary(
                '/sqlparser.SqlParser/Dialects',
                request_serializer=sqlparser__pb2.DialectsRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.DialectsReply.FromString,
                _registered_method=True)
        self.Parse = channel.unary_unary(
                '/sqlparser.SqlParser/Parse',
                request_serializer=sqlparser__pb2.ParseRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.ParseReply.FromString,
                _registered_method=True)
        self.Transpile = channel.unary_unary(
                '/sqlparser.SqlParser/Transpile',
                request_serializer=sqlparser__pb2.TranspileRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.TranspileReply.FromString,
                _registered_method=True)
        self.Format = channel.unary_unary(
                '/sqlparser.SqlParser/Format',
                request_serializer=sqlparser__pb2.FormatRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.FormatReply.FromString,
                _registered_method=True)
        self.Validate = channel.unary_unary(
                '/sqlparser.SqlParser/Validate',
                request_serializer=sqlparser__pb2.ValidateRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.ValidateReply.FromString,
                _registered_method=True)
        self.Extract = channel.unary_unary(
                '/sqlparser.SqlParser/Extract',
                request_serializer=sqlparser__pb2.ExtractRequest.SerializeToString,
                response_deserializer=sqlparser__pb2.ExtractReply.FromString,
                _registered_method=True)


class SqlParserServicer(object):
    """SQL 解析服务 —— 基于 sqlglot
    """

    def Health(self, request, context):
        """健康检查
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Dialects(self, request, context):
        """列出支持的方言
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Parse(self, request, context):
        """解析为 AST
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Transpile(self, request, context):
        """方言互转
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Format(self, request, context):
        """格式化
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Validate(self, request, context):
        """语法校验
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Extract(self, request, context):
        """提取元数据
        """
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_SqlParserServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Health': grpc.unary_unary_rpc_method_handler(
                    servicer.Health,
                    request_deserializer=sqlparser__pb2.HealthRequest.FromString,
                    response_serializer=sqlparser__pb2.HealthReply.SerializeToString,
            ),
            'Dialects': grpc.unary_unary_rpc_method_handler(
                    servicer.Dialects,
                    request_deserializer=sqlparser__pb2.DialectsRequest.FromString,
                    response_serializer=sqlparser__pb2.DialectsReply.SerializeToString,
            ),
            'Parse': grpc.unary_unary_rpc_method_handler(
                    servicer.Parse,
                    request_deserializer=sqlparser__pb2.ParseRequest.FromString,
                    response_serializer=sqlparser__pb2.ParseReply.SerializeToString,
            ),
            'Transpile': grpc.unary_unary_rpc_method_handler(
                    servicer.Transpile,
                    request_deserializer=sqlparser__pb2.TranspileRequest.FromString,
                    response_serializer=sqlparser__pb2.TranspileReply.SerializeToString,
            ),
            'Format': grpc.unary_unary_rpc_method_handler(
                    servicer.Format,
                    request_deserializer=sqlparser__pb2.FormatRequest.FromString,
                    response_serializer=sqlparser__pb2.FormatReply.SerializeToString,
            ),
            'Validate': grpc.unary_unary_rpc_method_handler(
                    servicer.Validate,
                    request_deserializer=sqlparser__pb2.ValidateRequest.FromString,
                    response_serializer=sqlparser__pb2.ValidateReply.SerializeToString,
            ),
            'Extract': grpc.unary_unary_rpc_method_handler(
                    servicer.Extract,
                    request_deserializer=sqlparser__pb2.ExtractRequest.FromString,
                    response_serializer=sqlparser__pb2.ExtractReply.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'sqlparser.SqlParser', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('sqlparser.SqlParser', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class SqlParser(object):
    """SQL 解析服务 —— 基于 sqlglot
    """

    @staticmethod
    def Health(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Health',
            sqlparser__pb2.HealthRequest.SerializeToString,
            sqlparser__pb2.HealthReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Dialects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Dialects',
            sqlparser__pb2.DialectsRequest.SerializeToString,
            sqlparser__pb2.DialectsReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Parse(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Parse',
            sqlparser__pb2.ParseRequest.SerializeToString,
            sqlparser__pb2.ParseReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Transpile(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Transpile',
            sqlparser__pb2.TranspileRequest.SerializeToString,
            sqlparser__pb2.TranspileReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Format(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Format',
            sqlparser__pb2.FormatRequest.SerializeToString,
            sqlparser__pb2.FormatReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Validate(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Validate',
            sqlparser__pb2.ValidateRequest.SerializeToString,
            sqlparser__pb2.ValidateReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Extract(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/sqlparser.SqlParser/Extract',
            sqlparser__pb2.ExtractRequest.SerializeToString,
            sqlparser__pb2.ExtractReply.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
